version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: autohub-postgres
    environment:
      POSTGRES_DB: autohub
      POSTGRES_USER: autohub_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_me_in_production}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autohub_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: autohub-backend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=autohub_user
      - DB_PASSWORD=${DB_PASSWORD:-change_me_in_production}
      - DB_NAME=autohub
      - JWT_SECRET=${JWT_SECRET:-change_me_in_production}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

